---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: nifi-znode
spec:
  clusterRef:
    name: zookeeper
---
apiVersion: v1
kind: Secret
metadata:
  name: nifi-admin-credentials
stringData:
  username: admin
  password: admin
---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: nifi
spec:
  version: 1.18.0-stackable0.1.0
  zookeeperConfigMapName: nifi-znode
  config:
    authentication:
      method:
        singleUser:
          adminCredentialsSecret: nifi-admin-credentials
          autoGenerate: true
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
  nodes:
    roleGroups:
      default:
        replicas: 2

# get nifi url if no stackablectl available (stackablectl svc list):
# nifi_node_name=$(kubectl get endpoints nifi --output=jsonpath='{.subsets[0].addresses[0].nodeName}') && echo "NodeName: $nifi_node_name"
# nifi_node_ip=$(kubectl get nodes -o jsonpath="{.items[?(@.metadata.name==\"$nifi_node_name\")].status.addresses[?(@.type==\"InternalIP\")].address}") && echo "NodeIp: $nifi_node_ip"
# nifi_service_port=$(kubectl get service -o jsonpath="{.items[?(@.metadata.name==\"nifi\")].spec.ports[?(@.name==\"https\")].nodePort}") && echo "NodePort: $nifi_service_port"
# nifi_url="https://$nifi_node_ip:$nifi_service_port" && echo "NiFi web interface: $nifi_url"
