---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: adminadmin
  connections.secretKey: thisISaSECRET_1234
  connections.sqlalchemyDatabaseUri: postgresql://admin:adminadmin@postgresql/test
---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  version: 1.5.1-stackable23.4.0-rc2
  statsdExporterVersion: v0.22.4
  credentialsSecret: superset-credentials
  loadExamplesOnInit: false
  nodes:
    roleGroups:
      default:
        replicas: 1
