# stackablectl operator install commons secret hive zookeeper
# helm install minio minio --repo https://charts.bitnami.com/bitnami --set auth.rootUser=admin --set auth.rootPassword=adminadmin
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  version: 403-stackable0.1.0
  catalogLabelSelector:
    matchLabels:
      trino: simple-trino
  coordinators:
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: 4Gi
    roleGroups:
      default:
        replicas: 1
  workers:
    config:
      resources:
        cpu:
          min: "2"
          max: "4"
        memory:
          limit: 6Gi
    roleGroups:
      default:
        replicas: 2
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: hive
  labels:
    trino: simple-trino
spec:
  connector:
    hive:
      metastore:
        configMap: simple-hive-derby
      s3:
        reference: minio
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-hive-derby
spec:
  version: 3.1.3-stackable0.1.0
  metastore:
    roleGroups:
      default:
        replicas: 1
        config:
          database:
            connString: jdbc:derby:;databaseName=/tmp/metastore_db;create=true
            user: APP
            password: mine
            dbType: derby
  s3:
    reference: minio
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: minio
spec:
  host: minio
  port: 9000
  accessStyle: Path
  credentials:
    secretClass: simple-s3-credentials-secret-class
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: simple-s3-credentials-secret-class
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-s3-credentials-secret
  labels:
    secrets.stackable.tech/class: simple-s3-credentials-secret-class
stringData:
  accessKey: admin
  secretKey: adminadmin
